# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
            ],
        ),
    ]
