# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('bid', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='书号')),
                ('bname', models.CharField(max_length=64, verbose_name='书名')),
                ('bauther', models.CharField(max_length=64, verbose_name='作者')),
                ('bpublisher', models.CharField(max_length=64, verbose_name='出版社')),
                ('bdata', models.DateField(verbose_name='出版日期')),
                ('bstore', models.IntegerField(verbose_name='库存')),
                ('bborrow', models.IntegerField(verbose_name='借阅量')),
            ],
        ),
    ]
