# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bborrow',
            field=models.IntegerField(default=0, verbose_name='借阅量'),
        ),
    ]
