# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20171121_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bdata',
            new_name='bdate',
        ),
    ]
