# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20171121_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bauther',
            new_name='bauthor',
        ),
    ]
