# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20171122_1058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookinfo',
            unique_together=set([('bid', 'bname', 'bauthor', 'bpublisher', 'bdate', 'bstore', 'bborrow')]),
        ),
    ]
