# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0006_studentinfo'),
        ('Books', '0003_auto_20171121_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowInfo',
            fields=[
                ('bdate', models.DateField(auto_created=True, auto_now_add=True)),
                ('bwid', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.BookInfo')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.StudentInfo')),
            ],
        ),
    ]
