# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Borrows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinfo',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='Books.BookInfo'),
        ),
        migrations.AlterField(
            model_name='borrowinfo',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='Student.StudentInfo'),
        ),
    ]
