# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(auto_created=True, max_length=15, unique=True, verbose_name='学号')),
                ('sname', models.CharField(max_length=15, verbose_name='姓名')),
                ('smajor', models.CharField(max_length=15, verbose_name='专业')),
                ('sclass', models.CharField(max_length=15, verbose_name='班级')),
                ('sphone', models.CharField(max_length=15, verbose_name='手机号')),
            ],
        ),
    ]
