# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='学号'),
        ),
    ]
