# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_studentinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
