# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_studentinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together=set([('sid', 'sname', 'smajor', 'sclass', 'sphone')]),
        ),
    ]
